service: aws-node-project1

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    name: typescript-hello-world
    events:
      - http: GET /

    
